### ISSUE TITLE
program stuck after done pre-decoding instructions for 'MESA_SHADER_MISS_func1_main"

### ISSUE THREAD

**Issue by liqingy5** [ubc-aamodt-group/trace-runner-vulkan-sim#1]
Hi, I install the Vulkan-sim and trace runner on EC2 Ubuntu 20.04.
I have set up the vulkan-sim and trace runner. Then I tried to running the traces with the workloads in the readme of this repo, however, for the some workloads, the program is stucking after showing message "done pre-decoding instructions for 'MESA_SHADER...", I waited about 40 mins before I kill the program. Is this normal? Should I wait longer ?

the workloads are:

./vulkan_rt_runner raytracing_extended_448x320/ raytracing_extended
./vulkan_rt_runner RayTracingInVulkan-Scene5-448x320-Baseline/ RayTracingInVulkan-Scene5
./vulkan_rt_runner RayTracingInVulkan-Scene6-448x320-Baseline/ RayTracingInVulkan-Scene6

<img width="968" alt="Screen Shot 2022-12-15 at 3 44 57 PM" src="https://user-images.githubusercontent.com/49260853/207971207-40c178fa-eab3-467b-86e3-94c6ff53c8f4.png">

**Comment by tommychouyc** [comment]
Hi, it is normal to see those messages. Those 3 workloads at those resolutions will take way more than 40 mins to complete at their full resolutions of 448x320.
I suggest trying a smaller resolution like 32x32 or 96x96 by editing the 0.callparams file in the workload folders. The second and third number in that file are the image width and height respectively. 
eg: 0,32,32,1,0 is to simulate a 32x32 image

On my computer with 96x96 resolutions, these are the run times under release mode.
raytracing_extended: 2 hrs
RayTracingInVulkan-Scene5: 1.5 hrs
RayTracingInVulkan-Scene6: 2 hrs

Please try a smaller resolution and let me know if the simulation still doesn't complete.

**Comment by liqingy5** [comment]
Thank you! The running time is faster after I change to 32x32. And also just to double check, when I saw this message,is this mean the simulation is completed successfully?
<img width="586" alt="Screen Shot 2022-12-15 at 10 18 19 PM" src="https://user-images.githubusercontent.com/49260853/208014522-068bc98c-a060-446c-a85a-a18b33b01298.png">

**Comment by tommychouyc** [comment]
Yes that means simulation finished! Glad it's working for you now.
